"""empty message

Revision ID: fa8b464dbad5
Revises: 32ea2603be50
Create Date: 2022-06-20 19:22:16.026409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8b464dbad5'
down_revision = '32ea2603be50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_login_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_login_key', 'users', ['login'])
    op.drop_constraint('session_date', 'sessions', type_='unique')
    # ### end Alembic commands ###
