services:
  shop_front:
    container_name: shop_front
    build:
      context: ./react_front
      dockerfile: ../Dockerfiles/React/Dockerfile
    command: npm start
    volumes:
      - "./react_front:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true



