name: React style check

on:
  push:
    branches:
      - main
    paths:
      - Front/react/**

  pull_request:

    branches:
      - main
    paths:
      - Front/react/**

  workflow_dispatch:

env:
  SRC_PATH: Front/react
  DEPLOY_PATH: Front/react

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.SRC_PATH }}

    strategy:
      matrix:
        node-version: [16.15.1]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npm run prettier

    - name: Run Eslint
      run: npm run  eslint || true
